package com.aura.mas.ui.navigation

object NavRoutes {
    const val LOGIN = "login"
    const val REGISTER = "register"
    const val MAIN = "main"
    const val DASHBOARD = "dashboard"
    const val PLAN_LIST = "plan_list"
    const val PLAN_CREATE = "plan_create"
    const val PLAN_DETAIL = "plan_detail/{planId}"
    const val NOTE_LIST = "note_list"
    const val NOTE_DETAIL = "note_detail/{noteId}"
    const val QUIZ_PLAYER = "quiz_player/{resourceId}"
    const val FLASHCARD_PLAYER = "flashcard_player/{noteId}"
    const val ANALYTICS = "analytics"
    const val KNOWLEDGE_TREE = "knowledge_tree/{planId}"
    const val KNOWLEDGE_GRAPH = "knowledge_graph/{userId}"
    const val PROFILE = "profile"
    const val SETTINGS = "settings"
    const val CACHE_MANAGEMENT = "cache_management"
    const val ADMIN_DASHBOARD = "admin_dashboard"
    const val ADMIN_USERS = "admin_users"
    const val ADMIN_LOGS = "admin_logs"
    const val CHAT = "chat"
    const val LEARNING_PROFILE = "learning_profile"
    const val PERSONAL_INFO_EDIT = "personal_info_edit"
    const val NOT_FOUND = "not_found"

    fun planDetail(planId: Long) = "plan_detail/$planId"
    fun noteDetail(noteId: Long) = "note_detail/$noteId"
    fun quizPlayer(resourceId: Long) = "quiz_player/$resourceId"
    fun flashcardPlayer(noteId: Long) = "flashcard_player/$noteId"
    fun knowledgeTree(planId: Long) = "knowledge_tree/$planId"
    fun knowledgeGraph(userId: Long) = "knowledge_graph/$userId"
}
